language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

before_script:
  - composer install --dev --no-interaction

script:
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
